# Generated by Django 2.2.2 on 2019-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190622_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='blog.Writer'),
        ),
    ]
