# Generated by Django 2.2.2 on 2019-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190622_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='genre_pics')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='blog.Genre')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
