# Generated by Django 2.2.2 on 2019-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190623_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='writer_pics'),
        ),
    ]
