# Generated by Django 2.2.2 on 2019-06-23 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_writer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
        migrations.AddField(
            model_name='book',
            name='writerofthebook',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='blog.Writer'),
        ),
        migrations.AddField(
            model_name='writer',
            name='Bio',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
