# Generated by Django 2.2.2 on 2019-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190623_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='the_genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='books',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='blog.Book'),
        ),
    ]
