# Generated by Django 2.2.2 on 2019-06-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_genre_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='books',
        ),
    ]
