# Generated by Django 2.2.2 on 2019-06-26 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_remove_comment_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profilepic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='enter your comment here', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
