# Generated by Django 2.2.2 on 2019-06-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20190626_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profilepic',
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
