# Generated by Django 2.2.2 on 2019-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190626_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookreview',
            field=models.TextField(default='enter your review here', max_length=1000),
        ),
    ]
