# Generated by Django 2.2.2 on 2019-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_book_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buying_link',
            field=models.CharField(default='link', max_length=300),
        ),
    ]
