# Generated by Django 2.2.2 on 2019-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_book_buying_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='knowmore',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='writer',
            name='penname',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
